### ISSUE TITLE
The pypi version is not same as the github version (0.9.27), has "we have " prompt under _0_init_tld.py

### ISSUE THREAD

**Issue by j0eii** [DannyCork/python-whois#278] opened 2023-02-13 09:05 UTC
## Describe the bug
pypi version is not sync with github version.

## To Reproduce
![image](https://user-images.githubusercontent.com/13985803/218415534-3a892da9-fef0-4f7e-9447-3eb7dc39cebd.png)
This is what i download from pypi https://pypi.org/project/whois/

## Expected behavior
version not sync

## Suggested mediation 
update the pypi version and sync with github version

**Comment by maarten-boot** [comment] 2023-02-13 11:03
yes confirmed, 
when installing a fresh copy via  pip install we do not get the same files as when we download the release: 
( https://github.com/DannyCork/python-whois/archive/refs/tags/0.9.27.tar.gz )

**Comment by falz** [comment] 2023-03-29 14:13
to be explicit, for folks getting 'we have com' or 'we have net' messages when doing lookups, this is why.

**Comment by tjaartvdwalt** [comment] 2023-04-11 22:46
This is present `0.9.27`, `0.9.26` and `0.9.25`.

It would be nice to have the latest version fixed in pip, since that is what most people will likely be downloading.

**Comment by maarten-boot** [comment] 2023-04-12 07:47
i have no access to publish to pipy so i am currently waiting for a response from the owner of the git repo, 
if none comes i will create a new clone and a new pipy entry so we can proceed with up-to date code, but with a new name ;-)

**Comment by maarten-boot** [comment] 2023-04-17 12:56
FYI:

a new pypi library exists now at: https://pypi.org/project/whoisdomain/

it is a cleaned up copy of this repo, i switched to versioning from 1.x.y where x is YYYYMMDD and y starts from 1 in case we need more then one pypi upload per day

the whois directory is renamed to whoisdomain and the package is released as whoisdomain , currently the actual code is unchanged

code is maintained at: https://github.com/mboot-github/WhoisDomain

when importing as :

import whoisdomain as whois
the rest of your code can stay the same

**Comment by falz** [comment] 2023-04-17 14:08
Thank you for this, just did some initial testing and working well.

**Closed** 2023-07-12 08:42 UTC
